### ISSUE TITLE
GameStates::Leaderboard crashes if the server is unavailable

### ISSUE THREAD

**Issue by Devnol** [Peter0x44/GeometrySlash#5]
If the connection to the server fails, entering GameStates::Leaderboard causes an EXC_BAD_ACCESS, since it is perhaps attempting to access nonexistent data. A proposed solution to this would be checking whether the server is available before switching states from ResultsScreen and throwing an error there, preventing Leaderboard from being entered.

**Comment by Peter0x44** [comment]
fixed in bf1609c8415a8dd0398fc82c99df4b63e84fcfb7
